### ISSUE TITLE
Sidekiq 3 compatibility

### ISSUE THREAD

**Issue by aaronchi** [wuputah/sidekiq-encryptor#5]
Is there any plan to upgrade this gem to work with sidekiq 3?

**Comment by aaronchi** [comment]
That was quick :)

**Comment by wuputah** [comment]
There ya go. Would appreciate feedback to know if it works fine or not. Think I should ship a `0.2.0pre` to Rubygems?

**Comment by wuputah** [comment]
Was something I had been meaning to do. :grin:

**Comment by aaronchi** [comment]
I will test tomorrow and let you know. Thanks!

**Comment by wuputah** [comment]
Awesome, thanks for raising this issue!

**Comment by aaronchi** [comment]
Testing and working. Thanks again :+1:

**Comment by wuputah** [comment]
:tada:
